plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.6'
}

group = 'com.rexcantor64.triton'

dependencies {
    compileOnly project(':api')
    compileOnly project(':core')
    compileOnly project(':core:triton-core-loader')

    annotationProcessor 'com.velocitypowered:velocity-api:3.4.0-SNAPSHOT'

    compileOnly 'com.velocitypowered:velocity-proxy:3.4.0-SNAPSHOT'

    compileOnly 'io.netty:netty-codec:4.1.80.Final'

    // FIXME in the future change this to dynamic download and loading
    implementation 'mysql:mysql-connector-java:8.0.30'

    implementation 'com.rexcantor64:libby-velocity:2.0.0'

    implementation 'org.bstats:bstats-velocity:3.1.0'

    compileOnly 'com.github.retrooper:packetevents-velocity:2.11.1'
}

shadowJar {
    archiveFileName = 'triton-velocity.jarinjar'

    relocate 'org.bstats', 'com.rexcantor64.triton.metrics'

    relocate 'net.byteflux.libby', 'com.rexcantor64.triton.lib.libby'
}
