plugins {
    id 'java'
    alias(libs.plugins.shadow)
}

group = 'com.rexcantor64.triton'

dependencies {
    compileOnly project(':api')
    compileOnly project(':core')
    compileOnly project(':core:triton-core-loader')

    annotationProcessor libs.velocity.api

    compileOnly libs.velocity.api
    compileOnly libs.velocity.proxy

    compileOnly libs.adventure.nbt

    compileOnly libs.netty.codec

    // FIXME in the future change this to dynamic download and loading
    implementation libs.mysql.connector

    implementation libs.libby.velocity

    implementation libs.bstats.velocity

    compileOnly libs.packetevents.velocity
}

shadowJar {
    archiveFileName = 'triton-velocity.jarinjar'

    relocate 'org.bstats', 'com.rexcantor64.triton.metrics'

    relocate 'net.byteflux.libby', 'com.rexcantor64.triton.lib.libby'
}
