plugins {
    id 'java'
    alias(libs.plugins.shadow)
}

apply plugin: 'com.gradleup.shadow'
group = 'com.rexcantor64.triton'

allprojects {
    apply plugin: 'java'
    version = '4.0.1'
    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }
    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            name = 'diogotcRepositoryReleases'
            url = 'https://repo.diogotc.com/releases/'
        }
        maven {
            name = 'diogotcRepositorySnapshots'
            url = 'https://repo.diogotc.com/snapshots/'
        }
        maven {
            url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'
            content {
                includeGroup 'org.bukkit'
                includeGroup 'org.spigotmc'
            }
        }
        maven { url = 'https://oss.sonatype.org/content/repositories/snapshots' }
        maven { url = 'https://repo.dmulloy2.net/nexus/repository/public/' }
        maven { url = 'https://repo.extendedclip.com/content/repositories/placeholderapi/' }
        maven {
            name = 'CodeMC'
            url = 'https://repo.codemc.org/repository/maven-public'
        }
        maven {
            name = 'papermc'
            url = 'https://repo.papermc.io/repository/maven-public/'
        }
        maven {
            // Mirror other people's repositories
            name = 'diogotcRepositoryMirror'
            url = 'https://repo.diogotc.com/mirror/'
        }
    }
}

subprojects {
    dependencies {
        compileOnly libs.jetbrains.annotations

        compileOnly libs.lombok
        annotationProcessor libs.lombok

        testCompileOnly libs.lombok
        testAnnotationProcessor libs.lombok
    }
}

dependencies {
    implementation project(':api')
    implementation project(':core:triton-core-loader')
    implementation project(':triton-bungeecord:triton-bungeecord-loader')
    implementation project(':triton-spigot:triton-spigot-loader')
    implementation project(':triton-velocity:triton-velocity-loader')

    compileOnly project(':core')
    compileOnly project(':triton-bungeecord')
    compileOnly project(':triton-spigot')
    compileOnly project(':triton-velocity')
}

shadowJar {
    getArchiveBaseName().set(rootProject.name)

    // Include .jarinjar files in the final build
    def modules = [':core', ':triton-bungeecord', ':triton-spigot', ':triton-velocity']
    modules.each { path ->
        def moduleProject = project(path)
        moduleProject.afterEvaluate {
            def shadowJarTask = moduleProject.tasks.named('shadowJar')
            from(shadowJarTask.flatMap { it.archiveFile })
        }
    }

    relocate 'org.objectweb.asm', 'com.rexcantor64.triton.lib.objectweb.asm'
    relocate 'me.lucko.jarrelocator', 'com.rexcantor64.triton.lib.jarrelocator'
}
