plugins {
    id 'java'
    alias(libs.plugins.shadow)
    alias(libs.plugins.blossom)
}

group = 'com.rexcantor64.triton'

test {
    useJUnitPlatform()
}

dependencies {
    compileOnly project(':core:triton-core-loader')
    compileOnly project(":api")

    // Adventure / MiniMessage
    compileOnly libs.adventure.serializer.gson
    compileOnly libs.adventure.serializer.legacy
    compileOnly libs.adventure.serializer.plain
    compileOnly libs.minimessage

    // Dependencies we can depend on, since they are on all platforms
    compileOnly libs.guava
    compileOnly libs.log4j.core
    compileOnly libs.snakeyaml

    compileOnly libs.packetevents.api

    compileOnly libs.bstats.base

    implementation libs.hikari
    implementation(libs.jsonpatch) {
        exclude group: 'com.google.code.gson', module: 'gson'
    }
    compileOnly libs.gson

    implementation libs.libby.core

    // Test dependencies
    testImplementation project(':core:triton-core-loader')
    testImplementation project(":api")

    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher

    testImplementation libs.adventure.api
    testImplementation libs.adventure.nbt
    testImplementation libs.adventure.serializer.gson
    testImplementation libs.adventure.serializer.legacy
    testImplementation libs.adventure.serializer.plain

    testImplementation libs.packetevents.api
    testImplementation libs.packetevents.netty.common
    testImplementation libs.netty.codec
}

shadowJar {
    archiveFileName = 'triton-core.jarinjar'

    relocate 'org.bstats', 'com.rexcantor64.triton.metrics'
    //relocate 'org.slf4j', 'com.rexcantor64.shaded.slf4j'
    relocate 'com.tananaev.jsonpatch', 'com.rexcantor64.shaded.jsonpatch'
    relocate 'com.zaxxer.hikari', 'com.rexcantor64.shaded.hikari'

    relocate 'net.byteflux.libby', 'com.rexcantor64.triton.lib.libby'

    relocate 'org.objectweb.asm', 'com.rexcantor64.triton.lib.objectweb.asm'
    relocate 'me.lucko.jarrelocator', 'com.rexcantor64.triton.lib.jarrelocator'
}

sourceSets {
    test {
        blossom {
            javaSources {
                property("adventure_version", libs.adventure.api.get().version)
                property("packet_events_version", libs.packetevents.api.get().version)
            }
        }
    }
}

import groovy.json.JsonOutput

abstract class GenerateFromEnumTask extends DefaultTask {

    @Input
    abstract Property<String> getEnumClassName()

    @Classpath
    abstract ConfigurableFileCollection getClasspath()

    @OutputDirectory
    abstract DirectoryProperty getOutputDir()

    @TaskAction
    void generate() {
        def urls = classpath.files.collect { it.toURI().toURL() } as URL[]
        def classLoader = new URLClassLoader(urls, (ClassLoader) null)

        try {
            def enumClass = classLoader.loadClass(enumClassName.get())
            if (!enumClass.isEnum()) {
                throw new GradleException("${enumClassName.get()} is not an enum")
            }

            def outputDirFile = outputDir.get().asFile
            outputDirFile.mkdirs()

            def values = enumClass.enumConstants.collect {
                value ->
                    [
                            groupId       : value.groupId,
                            artifactId    : value.artifactId,
                            version       : value.version,
                            sha256Checksum: value.sha256Checksum
                    ]
            }

            def file = new File(outputDirFile, "libby-libs.json")
            file.text = JsonOutput.toJson(values)
        } finally {
            classLoader.close()
        }
    }
}

tasks.register('genLibbyLibsJson', GenerateFromEnumTask) {
    enumClassName = "com.rexcantor64.triton.dependencies.Dependency"
    outputDir = layout.buildDirectory.dir("generated")

    classpath.from(sourceSets.main.runtimeClasspath).from(sourceSets.main.compileClasspath)
}
