plugins {
    id 'java'
    alias(libs.plugins.shadow)
}

group = 'com.rexcantor64.triton'

test {
    useJUnitPlatform()
}

dependencies {
    compileOnly project(':core:triton-core-loader')
    compileOnly project(":api")

    // Adventure / MiniMessage
    compileOnly libs.adventure.serializer.gson
    compileOnly libs.adventure.serializer.legacy
    compileOnly libs.adventure.serializer.plain
    compileOnly libs.minimessage

    // Dependencies we can depend on, since they are on all platforms
    compileOnly libs.guava
    compileOnly libs.log4j.core
    compileOnly libs.snakeyaml

    compileOnly libs.packetevents.api

    implementation libs.slf4j.nop
    implementation libs.hikari
    implementation(libs.jsonpatch) {
        exclude group: 'com.google.code.gson', module: 'gson'
    }
    compileOnly libs.gson

    implementation libs.libby.core

    // Test dependencies
    testImplementation project(":api")

    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher

    testImplementation libs.adventure.api
    testImplementation libs.adventure.serializer.gson
    testImplementation libs.adventure.serializer.legacy
    testImplementation libs.adventure.serializer.plain
}

shadowJar {
    archiveFileName = 'triton-core.jarinjar'

    relocate 'org.bstats', 'com.rexcantor64.triton.metrics'
    //relocate 'org.slf4j', 'com.rexcantor64.shaded.slf4j'
    relocate 'com.tananaev.jsonpatch', 'com.rexcantor64.shaded.jsonpatch'
    relocate 'com.zaxxer.hikari', 'com.rexcantor64.shaded.hikari'

    relocate 'net.byteflux.libby', 'com.rexcantor64.triton.lib.libby'

    relocate 'org.objectweb.asm', 'com.rexcantor64.triton.lib.objectweb.asm'
    relocate 'me.lucko.jarrelocator', 'com.rexcantor64.triton.lib.jarrelocator'
}
