plugins {
    id 'java'
    alias(libs.plugins.shadow)
}

group = 'com.rexcantor64.triton'

test {
    useJUnitPlatform()
}

dependencies {
    compileOnly project(':core:triton-core-loader')
    compileOnly project(':api')
    compileOnly project(':core')
    implementation project(':spigot-legacy')
    implementation project(':triton-spigot:triton-spigot-common')
    implementation project(':triton-spigot:triton-spigot-folia')

    compileOnly libs.spigot.api

    compileOnly libs.adventure.serializer.gson
    compileOnly libs.adventure.serializer.legacy
    compileOnly libs.adventure.serializer.bungeecord

    compileOnly libs.protocollib
    compileOnly libs.placeholderapi

    compileOnly libs.packetevents.spigot

    // Libraries available on Spigot
    compileOnly libs.jansi // Used for terminal translation

    implementation libs.libby.bukkit

    implementation libs.bstats.bukkit

    // Test dependencies
    testImplementation project(":api")

    testImplementation libs.spigot.api

    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
}

shadowJar {
    archiveFileName = 'triton-spigot.jarinjar'

    relocate 'org.bstats', 'com.rexcantor64.triton.metrics'

    relocate 'net.byteflux.libby', 'com.rexcantor64.triton.lib.libby'
}
