plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.6'
}

group = 'com.rexcantor64.triton'

test {
    useJUnitPlatform()
}

dependencies {
    compileOnly project(':core:triton-core-loader')
    compileOnly project(':api')
    compileOnly project(':core')
    implementation project(':spigot-legacy')

    compileOnly 'org.spigotmc:spigot-api:1.21.1-R0.1-SNAPSHOT'

    compileOnly 'net.kyori:adventure-text-serializer-gson:4.25.0'
    compileOnly 'net.kyori:adventure-text-serializer-legacy:4.25.0'
    compileOnly 'net.kyori:adventure-text-serializer-bungeecord:4.4.1'

    compileOnly 'com.comphenix.protocol:ProtocolLib:5.4.0-SNAPSHOT'
    compileOnly 'me.clip:placeholderapi:2.11.6'

    compileOnly 'com.github.retrooper:packetevents-spigot:2.11.0'

    // Libraries available on Spigot
    compileOnly 'org.fusesource.jansi:jansi:2.4.0' // Used for terminal translation

    implementation 'com.rexcantor64:libby-bukkit:2.0.0'

    implementation 'org.bstats:bstats-bukkit:3.1.0'

    // Test dependencies
    testImplementation project(":api")

    testImplementation 'org.spigotmc:spigot-api:1.21.1-R0.1-SNAPSHOT'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.0'
}

shadowJar {
    archiveFileName = 'triton-spigot.jarinjar'

    relocate 'org.bstats', 'com.rexcantor64.triton.metrics'

    relocate 'net.byteflux.libby', 'com.rexcantor64.triton.lib.libby'
}
