plugins {
    id 'java'
    alias(libs.plugins.blossom)
}

apply plugin: 'net.kyori.blossom'
group = 'com.rexcantor64.triton'

dependencies {
    compileOnly project(':core:triton-core-loader')

    compileOnly libs.velocity.proxy
    annotationProcessor libs.velocity.api
}

blossom {
    replaceToken '@version@', project.version
}
