plugins {
    id 'java'
    alias(libs.plugins.blossom)
}

group = 'com.rexcantor64.triton'

dependencies {
    compileOnly project(':core:triton-core-loader')

    compileOnly libs.velocity.proxy
    annotationProcessor libs.velocity.api
}

sourceSets {
    main {
        blossom {
            javaSources {
                property("version", project.provider { project.version.toString() })
            }
        }
    }
}
