package com.cloutteam.rex.multilanguage.banners;

import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.BannerMeta;

/**
 * @category Spigot/Bukkit only
 * 
 * @author Rexcantor64
 *
 */
public class Banner {

	/**
	 * Create a banner using the encoded code
	 * 
	 * @param encoded
	 *            The encoded code. From the config: "This is the encoded flag
	 *            code to show up the banner. To get a working code, you should
	 *            visit http://www.needcoolshoes.com/banner and create your
	 *            banner. When you finish, you should notice that the link as
	 *            changed. Just copy the code generated by it. i.e. If the link
	 *            is http://www.needcoolshoes.com/banner?=eapwplpnpmbzbj then
	 *            the code will be eapwplpnpmbzbj"
	 * @author Rexcantor64
	 *
	 */
	public Banner(String encoded) {
	}

	/**
	 * @return A clone of the BannerMeta. This doesn't contain any name, lore or
	 *         enchantment
	 * @author Rexcantor64
	 */
	public BannerMeta getMeta() {
		return null;
	}

	/**
	 * @return A clone of the ItemStack with the BannerMeta. This doesn't
	 *         contain any name, lore or enchantment
	 * @author Rexcantor64
	 */
	public ItemStack toBukkit() {
		return null;
	}

}
