plugins {
    id 'java'
    alias(libs.plugins.shadow)
}

group = 'com.rexcantor64.triton'

dependencies {
    compileOnly project(':core:triton-core-loader')
    compileOnly project(':api')
    compileOnly project(':core')

    compileOnly libs.bungeecord.api
    compileOnly libs.bungeecord.proxy

    compileOnly libs.adventure.serializer.bungeecord

    implementation libs.libby.bungee

    implementation libs.bstats.bungeecord

    compileOnly libs.packetevents.bungeecord
}

shadowJar {
    archiveFileName = 'triton-bungeecord.jarinjar'

    relocate 'org.bstats', 'com.rexcantor64.triton.metrics'

    relocate 'net.byteflux.libby', 'com.rexcantor64.triton.lib.libby'
}
