plugins {
    id 'java'
    id 'maven-publish'
}

group = 'com.rexcantor64.triton'

apply from: '../gradle/publish.gradle'

dependencies {
    compileOnly libs.spigot.api
    compileOnly libs.bungeecord.api

    compileOnly libs.adventure.api
    compileOnly libs.adventure.serializer.gson
}

java {
    withJavadocJar()
    withSourcesJar()
}

jar {
    from sourceSets.main.output
    manifest {
        attributes 'Automatic-Module-Name': 'com.rexcantor64.triton.api'
    }
}

javadoc {
    options.encoding = 'UTF-8'
    options.charSet = 'UTF-8'
    options.links(
            'https://hub.spigotmc.org/javadocs/spigot/',
            'https://jd.papermc.io/waterfall/1.21/', // Use Waterfall's JavaDocs instead of Bungee's since those are broken
            'https://docs.oracle.com/en/java/javase/25/docs/api/',
            "https://jd.papermc.io/adventure/${libs.adventure.api.get().version}/",
    )

    // Disable the crazy super-strict doclint tool
    options.addStringOption('Xdoclint:none', '-quiet')

    // Mark sources as Java 17 source compatible
    options.source = '17'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            artifactId = 'triton-api'

            pom {
                name.set('Triton API')
                description.set('Translate your server! Sends the same message in different languages... Hooks into all plugins!')
                url.set('https://triton.rexcantor64.com')
                scm {
                    url.set('https://github.com/tritonmc/Triton')
                    connection.set('scm:git:https://github.com/tritonmc/Triton.git')
                    developerConnection.set('scm:git:https://github.com/tritonmc/Triton.git')
                }
            }
        }
    }
}
