name: Release

on:
  release:
    types: [published]

jobs:
  libby-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up JDK 25
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-provider: basic

      - name: Install nix
        uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c # v31.10.7
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Generate libby json
        run: ./gradlew genLibbyLibsJson

      - name: Generate libby zip
        run: nix-build ./build-support/gen-libby-zip.nix -A libsZip --argstr tritonVersion ${{github.event.release.tag_name}}

      - name: Upload zip to release
        run: gh release upload ${{github.event.release.tag_name}} ./result/*.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
  publish-api-javadocs:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up JDK 25
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-provider: basic

      - name: Publish package
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_diogotcRepositoryUsername: github-ci-triton
          ORG_GRADLE_PROJECT_diogotcRepositoryPassword: ${{ secrets.MAVEN_REPO_SECRET }}
